sudo: false
language: python
services:
- memcached
- postgresql
- redis-server
python:
- '2.7'
cache:
  directories:
  - node_modules
  - "$HOME/.cache/pip"
deploy:
- provider: pypi
  user: max-wittig
  password:
    secure: "D5OHhp/WS2OAdXozy8s31FAOoJM77BWDIDXCd8dLNmY15MV2NeXUeOT+gNiwv+7Rawdxd5VvFqqn5641bO1yTECsSDIF8joSXU8Hn8k6P6KEU9rhEC/PohrGm9dSO7xy2RdizCnh75Cl8wZ1pcsVH7ExD0H4/Dmp/352f4iD3ELUFRxdpfNx/Dk+nyfdPN53uj5vHXNEXOLXpA8h0G1SFlw+YRYEcZRk4GijhD6hMPnvvSkreIFxW7rhbi2gnVvhxl4TxKRKwQutQVeNe6B9cpw8tuDJfYqM76EJWAEtcciaWyIS5aqaqKPjwktTgkwV+xpRbkPx6Za9Xd3ZTz38nqEIVW6kJFkxyLIUOjUJiMGS4BvRKuhsHSLFOqjgdsQa2dwptIsrdsgDQNFLYroBJAGNnhPBWrIv6vKCL+jTbWTJINPtsnQh4QBLUCYaZdjHG/L0qT68UNRrjTNu7R1Q6hhm6L9Rsp11l1wL8S/3h2TfinU2OHmMTKfLUZcoUh5/H9crOn490NQ1YzFpsV+WlGy3WuvqG6c7ugl2TJ7RHqq4wgYbeVYOoniqBdpAqiLFDp8UUAVZUrigfw/hBgdgBtnw6AlaMgPOlltZflig9GC54jmZAsZK54kGKXt8oPeLMF2ipFiY0sXoVCxbC2HhbDX8yK+tIXBqYJ+fM5fF76w="
  distributions: sdist bdist_wheel
  on:
    tags: true
env:
  global:
  - PIP_DOWNLOAD_CACHE=".pip_download_cache"
  - PIP_DISABLE_PIP_VERSION_CHECK=on
  - SENTRY_SKIP_BACKEND_VALIDATION=1
before_install:
- npm install -g npm@latest
- pip install codecov
- pip install -U setuptools
install:
- make develop
script:
- PYFLAKES_NODOCTEST=1 flake8
- coverage run --source=. -m py.test tests
after_success:
- codecov
